server:
  port: 8401
spring:
  datasource:
    druid:
      url: jdbc:mysql://mysql-min:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: reader
      password: 123456
      initial-size: 40 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 80 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: cloud-redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
# 自定义redis key
redis:
  database: mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  # 启用 okhttp 关闭默认 httpclient
  httpclient:
    enabled: false #关闭httpclient
    # 配置连接池
    max-connections: 200 #feign的最大连接数
    max-connections-per-route: 50 #fegin单个路径的最大连接数
  okhttp:
    enabled: true
  # 请求与响应的压缩以提高通信效率
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
ribbon:
  ConnectTimeout: 10000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 10000 #服务请求处理超时时间（毫秒）

okhttp:
  maxIdleConnections: 100

auth:
  # 认证时auth是否直接读取缓存，1读取缓存
  cacheSwitch: 1
  # MD5认证时是否要求密码匹配，1要求密码匹配
  matchSwitch: 1